### ISSUE TITLE
training slow

### ISSUE THREAD

**Issue by q-learning-trader** [hijkzzz/reinforcement-learning-trading-robot#1]
Nice concept, thanks for sharing @hijkzzz 
I have a laptop with GPU and training is very slow.
Training 10000 epochs takes several hours and I haven't tried 100000 epochs yet but I think it would take some days.
Do you have any insight on how to train faster?

**Comment by hijkzzz** [comment]
You can train in parallel like A2C, the efficiency will be much higher.

**Comment by q-learning-trader** [comment]
If I understand well, in case of parallel execution, the code should read params.py file before each episode, can you confirm it ?

**Comment by hijkzzz** [comment]
You should modify the code to collect samples in parallel and then train them all at once
